### ISSUE TITLE
[1.20.1 Forge] Ticking Error crash, XP Tome possibly involved

### ISSUE THREAD

**Issue by PlayfulPiano** [jaredlll08/Clumps#128] opened 2023-12-05 21:28 UTC
Hey there, I just experienced a crash that the log pointed towards clumps being the potential cause. I right clicked an XP Tome (https://www.curseforge.com/minecraft/mc-mods/xp-tome) that had some xp stored so I could repair my mending pickaxe on hand, and it caused this crash while in the nether.
[crash-2023-12-05_16.24.45-server.txt](https://github.com/jaredlll08/Clumps/files/13573095/crash-2023-12-05_16.24.45-server.txt)

Using Forge 47.2.8, Clumps 12.0.0.3, and XP Tome 2.2 when this happened. I've done this exact behavior before without any crash so I'm unsure what specific caused it.

**Comment by jaredlll08** [comment] 2023-12-05 21:34
can you please screenshot the tooltip of your mending pickaxe please.

**Comment by PlayfulPiano** [comment] 2023-12-05 22:03
![image](https://github.com/jaredlll08/Clumps/assets/3158887/c8b289a0-9764-45a5-b175-69e117f90901)

**Comment by jaredlll08** [comment] 2023-12-05 22:34
Are you able to reproduce the crash?

**Comment by PlayfulPiano** [comment] 2023-12-05 22:39
no, this is the first time and only time this has happened / I've done similar behaviors before/after with no crash.

Only thing I could maybe think of here is due to AdvancedNetherite's higher durability values causing some issue with the mending process. Otherwise I don't know.

**Comment by PlayfulPiano** [comment] 2023-12-05 22:39
Also after the crash my tool was properly repaired and the xp was given with no like xp duplication, so the process did save.

**Comment by jaredlll08** [comment] 2023-12-06 05:39
Would you be able to do a test by having the pickaxe at a very low durability and then using the xp tomb to repair it, and see if it works or not.

**Comment by jaredlll08** [comment] 2024-04-22 22:41
Closing due to no reply and no one else reporting the same.

**Closed as not planned by jaredlll08** 2024-04-22 22:41 UTC
