### ISSUE TITLE
This makes the game crash

### ISSUE THREAD

**Issue by red-ornob** [jaredlll08/Clumps#66] opened 2021-06-11 12:25 UTC
My game crashes when I enter the nether, when after removing Clumps. it worked again.
I'll provide the crash log. dunno what they mean. and they say about sodium and chorine but they do not cause the crash its not crashing anymore.

[crash-2021-06-11_17.25.21-client.txt](https://github.com/jaredlll08/Clumps/files/6638327/crash-2021-06-11_17.25.21-client.txt)

**Comment by jaredlll08** [comment] 2021-06-11 15:24
Clumps I'm guessing is not compatible with Sodium.

Report it to Sodium, I'm not interested in making my code *less* performant just so it doesn't cause issues with *performance* mods trying to be *more* performant, those mods shouldn't be doing it like this in the first place and are bound to cause issues with other mods as well.


There has also been an issue with the Performant mod, but I believe that has been fixed on their side already, and the log mentions sodium as the cause.

**Closed as completed by jaredlll08** 2021-06-11 15:24 UTC
