### ISSUE TITLE
[Suggestion] Clumps on Modrinth

### ISSUE THREAD

**Issue by Eiion** [jaredlll08/Clumps#113] opened 2023-01-09 11:03 UTC
Would you please make Clumps available via Modrinth as well?
Thanks for considering in advance.

**Comment by jaredlll08** [comment] 2023-01-10 21:39
Duplicate of https://github.com/jaredlll08/Clumps/issues/98

**Closed as not planned by jaredlll08** 2023-01-10 21:39 UTC

**Comment by jaredlll08** [comment] 2023-06-10 00:07
https://modrinth.com/user/jaredlll08
